# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Рассказ', 'verbose_name_plural': 'Рассказы'},
        ),
        migrations.AddField(
            model_name='post',
            name='tpublish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
